name: 'Terraform'

on:
  push:
    branches:
    - main
  pull_request:


jobs:
  terraform:
    name: 'Terraform'
    env:
      ARM_CLIENT_ID: ${{ secrets.AZURE_AD_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.AZURE_AD_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_AD_TENENT_ID }}
      ROOT_PATH: '${{github.workspace}}/rsg'
    runs-on: ubuntu-latest
    environment: dev

    defaults:
      run:
        shell: bash
    steps:
    - name: Checkout
      uses: hashicorp/setup-terraform@v3
    
    - name: 'Terraform-Format'
      uses: hashicorp/setup-terraform
      with: 
        tf_actions_version: 1.7.3
        tf_actions_subcommand: 'fmt'
        working-directory: ${{env.ROOT_PATH}}

    - name: 'Terraform Init'
      uses: hashicorp/setup-terraform
      with: 
        tf_actions_version: 1.7.3
        tf_actions_subcommand: 'init'
        working-directory: ${{env.ROOT_PATH}}
       

    

    - name: 'Terraform validate'
      uses: hashicorp/setup-terraform
      with: 
        tf_actions_version: 1.7.3
        tf_actions_subcommand: 'validate'
        working-directory: ${{env.ROOT_PATH}}
       

    - name: 'Terraform plan'
      uses: hhashicorp/setup-terraform
      with: 
        tf_actions_version: 1.7.3
        tf_actions_subcommand: 'plan'
        working-directory: ${{env.ROOT_PATH}}
   


    - name: 'Terraform validate'
      uses: hashicorp/setup-terraform
      with: 
        tf_actions_version: 1.7.3
        tf_actions_subcommand: 'apply'
        working-directory: ${{env.ROOT_PATH}}

